In [1]:
from torch import tensor
from torch.nn import Linear,Parameter

In [6]:
w = tensor([[2.5]],requires_grad=True)
b = tensor([90.0],requires_grad=True)
lr = Linear(in_features=1,out_features=1,bias=True)
lr.weight = Parameter(w)
lr.bias = Parameter(b)
x = tensor([[5.0]])
y = lr(x)
print(y)

tensor([[102.5000]], grad_fn=<AddmmBackward0>)


In [7]:
x = tensor([[1.0,2.0,3.0]])
lr = Linear(in_features=3,out_features=1,bias=True)
y = lr(x)
print(y)

tensor([[-0.4869]], grad_fn=<AddmmBackward0>)


In [8]:
lr.state_dict()

OrderedDict([('weight', tensor([[ 0.5059, -0.5321,  0.0280]])),
             ('bias', tensor([-0.0125]))])

In [9]:
from torch.nn import ReLU
relu = ReLU()

In [11]:
from re import L
from torch.nn import Sequential
deep_lr = Sequential(Linear(in_features=2,out_features=4,bias=True),ReLU(),Linear(in_features=4,out_features=3,bias=True),Linear(in_features=3,out_features=1,bias=True),ReLU())
X = tensor([[1.0,2.0]])
y = deep_lr(X)
print(y)

tensor([[0.]], grad_fn=<ReluBackward0>)
